apiVersion: apps/v1
kind: Deployment
metadata:
  name: modmail-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: modmail-bot
  template:
    metadata:
      labels:
        app: modmail-bot
    spec:
      containers:
        - name: modmail-bot
          image: kyb3rr/modmail:latest
          resources:
            requests:
              cpu: 10m
              memory: 200Mi
            limits:
              cpu: 20m
              memory: 300Mi
          imagePullPolicy: "Always"
          envFrom:
            - secretRef:
                name: modmail
