kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pypi-storage
  labels:
    app: pypi-server
spec:
  storageClassName: linode-block-storage-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
