apiVersion: apps/v1
kind: Deployment
metadata:
  name: site
spec:
  replicas: 2
  selector:
    matchLabels:
      app: site
  template:
    metadata:
      labels:
        app: site
    spec:
      containers:
        - name: site
          image: ghcr.io/python-discord/site:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /
              port: 8000
              httpHeaders:
                - name: Host
                  value: pythondiscord.com
            failureThreshold: 2
            periodSeconds: 30
            timeoutSeconds: 5
            initialDelaySeconds: 10
          startupProbe:
            httpGet:
              path: /
              port: 8000
              httpHeaders:
                - name: Host
                  value: pythondiscord.com
            failureThreshold: 15
            periodSeconds: 2
            timeoutSeconds: 5
            initialDelaySeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 1000Mi
            requests:
              cpu: 250m
              memory: 400Mi
          envFrom:
            - secretRef:
                name: site-env
            - secretRef:
                name: sentry-env
          volumeMounts:
            - name: django-staticfiles
              mountPath: /app/staticfiles
            - name: django-bulma-dodgy-mount-fix
              mountPath: /usr/local/lib/python3.9/site-packages/django_simple_bulma/css/
            - name: django-bulma-dodgy-mount-fix-futureproof
              mountPath: /usr/local/lib/python3.10/site-packages/django_simple_bulma/css/
            - name: django-tmp
              mountPath: /tmp
          securityContext:
            readOnlyRootFilesystem: true
      volumes:
      - name: django-staticfiles
        emptyDir: {}
      - name: django-bulma-dodgy-mount-fix
        emptyDir: {}
      - name: django-bulma-dodgy-mount-fix-futureproof
        emptyDir: {}
      - name: django-tmp
        emptyDir:
          medium: Memory
