apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: site-cloudflare-access
spec:
  forwardAuth:
    address: http://traefik-auth-cloudflare.default.svc.cluster.local:80/auth/087eaf0280d38585c26251e1a66cac0796a699e07c5213cec6732676ca408461
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: site
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`pythondiscord.com`) || Host(`api.pythondiscord.com`)
    kind: Rule
    services:
    - name: site
      port: 80
    middlewares:
    - name: global-chain
  - match: Host(`staff.pythondiscord.com`)
    kind: Rule
    services:
    - name: site
      port: 80
    middlewares:
    - name: site-cloudflare-access
    - name: global-chain
  tls:
    certResolver: cfresolver
    domains:
    - main: "*.pythondiscord.com"
      sans: [pythondiscord.com]
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: internal-api
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`pydis-api.default.svc.cluster.local`)
    kind: Rule
    services:
    - name: site
      port: 80
