apiVersion: v1
kind: Service
metadata:
  name: site
spec:
  selector:
    app: site
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: pydis-api
spec:
  selector:
    app: site
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
