apiVersion: v1
kind: Service
metadata:
  name: traefik-internal
  namespace: kube-system
spec:
  selector:
    app.kubernetes.io/instance: traefik
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
