ingressClass:
  enabled: true
  isDefaultClass: true

deployment:
  initContainers:
    - name: volume-permissions
      image: busybox:1.31.1
      command: ["sh", "-c", "chmod -Rv 600 /data/*"]
      volumeMounts:
        - name: data
          mountPath: /data

logs:
  general:
    # Available levels: DEBUG, PANIC, FATAL, ERROR, WARN, and INFO.
    level: INFO
  access:
    # To enable access logs
    enabled: false

ports:
  websecure:
    tls:
      enabled: true
      certResolver: "cfresolver"

globalArguments:
  - "--global.checknewversion"

additionalArguments:
  - "--certificatesresolvers.cfresolver=true"
  - "--certificatesresolvers.cfresolver.acme.dnschallenge=true"
  - "--certificatesresolvers.cfresolver.acme.dnschallenge.provider=cloudflare"
  - "--certificatesresolvers.cfresolver.acme.email=letsencrypt@pythondiscord.com"
  - "--certificatesresolvers.cfresolver.acme.storage=/certs/acme.json"
  - "--providers.kubernetesingress=true"
  - "--api.dashboard=true"
  - "--metrics.prometheus=true"

envFrom:
  - secretRef:
      name: cloudflare-credentials

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi
  storageClass: "linode-block-storage-retain"
  path: /certs
  annotations: {}
