ingressClass:
  enabled: true
  isDefaultClass: true

deployment:
  enabled: true
  kind: DaemonSet

logs:
  general:
    # Available levels: DEBUG, PANIC, FATAL, ERROR, WARN, and INFO.
    level: INFO
  access:
    # To enable access logs
    enabled: false

pilot:
  enabled: true
  token: '9643ed70-f03f-4d3d-9792-df3142906ff4'
  dashboard: true

ports:
  websecure:
    tls:
      enabled: true

globalArguments:
  - "--global.checknewversion"

additionalArguments:
  - "--providers.kubernetesingress=true"
  - "--api.dashboard=true"
  - "--metrics.prometheus=true"

persistence:
  enabled: false
