apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`grafana.pythondiscord.com`)
    kind: Rule
    services:
    - name: grafana
      port: 3000
    middlewares:
    - name: global-chain
  tls:
    certResolver: cfresolver
    domains:
    - main: "*.pythondiscord.com"
