---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: king-arthur
rules:
- apiGroups: ["", "extensions", "apps", "batch", "rbac.authorization.k8s.io", "cert-manager.io"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: king-arthur
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: king-arthur
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: king-arthur
subjects:
  - kind: ServiceAccount
    name: king-arthur
    namespace: default
