apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-internal
  namespace: kube-system
spec:
  selector:
    app.kubernetes.io/instance: ingress-nginx
  ports:
    - protocol: TCP
      port: 80
      name: http
      targetPort: 80
    - protocol: TCP
      port: 443
      name: https
      targetPort: 443
