apiVersion: apps/v1
kind: Deployment
metadata:
  name: pixels
spec:
  replicas: 0
  selector:
    matchLabels:
      app: pixels
  template:
    metadata:
      labels:
        app: pixels
    spec:
      containers:
        - name: pixels
          image: ghcr.io/python-discord/pixels:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
          envFrom:
            - secretRef:
                name: pixels-env
          startupProbe:
            httpGet:
              path: /size
              port: http
              httpHeaders:
                - name: Host
                  value: pixels.pythondiscord.com
            failureThreshold: 15
            periodSeconds: 1
          securityContext:
            readOnlyRootFilesystem: true
      imagePullSecrets:
        - name: ghcr-credentials
      securityContext:
        fsGroup: 2000
        runAsUser: 1000
        runAsNonRoot: true
