apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 27017
          resources:
            requests:
              cpu: 10m
              memory: 200Mi
            limits:
              cpu: 50m
              memory: 300Mi
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-volume
          envFrom:
          - secretRef:
              name: mongo-credentials
      volumes:
        - name: mongodb-volume
          persistentVolumeClaim:
            claimName: mongodb-storage
