apiVersion: v1
kind: ConfigMap
metadata:
  name: superset-config
data:
  superset_config.py: |
    import os
    from cachelib.redis import RedisCache

    def env(key, default=None):
      return os.getenv(key, default)

    SUPERSET_WEBSERVER_PROTOCOL = "https"
    SECRET_KEY = env('SECRET_KEY')
    SQLALCHEMY_DATABASE_URI = f"postgresql+psycopg2://{env('DATABASE_USER')}:{env('DATABASE_PASSWORD')}@{env('DATABASE_HOST')}:{env('DATABASE_PORT')}/{env('DATABASE_DB')}"

    class CeleryConfig(object):
      BROKER_URL = f"redis://:{env('REDIS_PASSWORD')}@{env('REDIS_HOST')}:{env('REDIS_PORT')}/3"
      CELERY_IMPORTS = ('superset.sql_lab', )
      CELERY_RESULT_BACKEND = f"redis://:{env('REDIS_PASSWORD')}@{env('REDIS_HOST')}:{env('REDIS_PORT')}/3"
      CELERY_ANNOTATIONS = {'tasks.add': {'rate_limit': '10/s'}}

    CELERY_CONFIG = CeleryConfig
    RESULTS_BACKEND = RedisCache(
          host=env('REDIS_HOST'),
          port=env('REDIS_PORT'),
          password=env('REDIS_PASSWORD'),
          db=3,
          key_prefix='superset_results'
    )
