apiVersion: v1
kind: ConfigMap
metadata:
  name: olli-config
data:
  olli.toml: |
    [olli]
    interval_minutes = 5

    [loki]
    api_url = "http://loki.loki.svc.cluster.local:3100/"
    jobs = [
        "default/bot",
        "default/site",
        "default/sir-lancebot",
        "default/metricity",
        "default/snekbox",
        "default/quackstack"
    ]

    [[olli.tokens]]
    token = "ERROR"
    color = "#ff5f5f"

    [[olli.tokens]]
    token = "WARN"
    color = "#ffe24d"
    case_sensitive = true
