apiVersion: apps/v1
kind: Deployment
metadata:
  name: modmail-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: modmail-bot
  template:
    metadata:
      labels:
        app: modmail-bot
    spec:
      containers:
        - name: modmail-bot
          image: ghcr.io/python-discord/modmail:1d241a1
          resources:
            requests:
              cpu: 50m
              memory: 350Mi
            limits:
              cpu: 100m
              memory: 500Mi
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /modmailbot/plugins
            name: plugins-vol
          - mountPath: /modmailbot/temp
            name: temp-vol
          envFrom:
            - secretRef:
                name: modmail
          securityContext:
            readOnlyRootFilesystem: true
      volumes:
      - name: plugins-vol
        emptyDir: {}
      - name: temp-vol
        emptyDir:
          medium: Memory
      securityContext:
        fsGroup: 2000
        runAsUser: 1000
        runAsNonRoot: true
