apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot
  template:
    metadata:
      labels:
        app: bot
    spec:
      containers:
      - name: bot
        image: ghcr.io/python-discord/bot:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 750m
            memory: 600Mi
          limits:
            cpu: 1000m
            memory: 800Mi
        envFrom:
        - secretRef:
            name: bot-env
        - secretRef:
            name: sentry-env
        - secretRef:
            name: redis-credentials
        volumeMounts:
        - mountPath: /bot/logs
          name: logs-vol
        securityContext:
          readOnlyRootFilesystem: true
      volumes:
      - name: logs-vol
        emptyDir: {}
