kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-storage
  labels:
    app: redis
spec:
  storageClassName: linode-block-storage-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
