kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-storage
  labels:
    app: postgres
spec:
  storageClassName: linode-block-storage-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
