apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: blackbox
spec:
  schedule: "0 15 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: blackbox
            image: lemonsaurus/blackbox:d4b821f
            imagePullPolicy: Always
            envFrom:
              - secretRef:
                  name: postgres-env
              - secretRef:
                  name: redis-credentials
              - secretRef:
                  name: mongo-credentials
              - secretRef:
                  name: s3-credentials
              - secretRef:
                  name: discord-webhooks
            env:
              - name: BLACKBOX_CONFIG_PATH
                value: "/blackbox/config_file/blackbox.yaml"
            volumeMounts:
              - mountPath: /blackbox/config_file
                name: blackbox-config
          volumes:
            - name: blackbox-config
              configMap:
                name: blackbox-config
          restartPolicy: OnFailure
          nodeSelector:
            # NOTE: This should be updated to match the highest spec
            # instance that is being used by the cluster.
            beta.kubernetes.io/instance-type: g6-standard-4
      backoffLimit: 3
