apiVersion: apps/v1
kind: Deployment
metadata:
  name: snekbox-310
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snekbox-310
  template:
    metadata:
      labels:
        app: snekbox-310
    spec:
      containers:
        - name: snekbox-310
          image: ghcr.io/python-discord/snekbox:2022.8.14.2
          imagePullPolicy: Always
          ports:
            - containerPort: 8060
          securityContext:
            privileged: true
