name: Manual Redeploy

on:
  workflow_dispatch:
    inputs:
      deployment:
        description: "The deployment to redeploy, options: bot, site, modmail-bot"
        required: true

jobs:
  validate_job:
    name: "Validate deployment"
    runs-on: ubuntu-latest

    steps:
      - name: Check if manual redeployment is allowed
        if: github.event.inputs.deployment != "bot" && github.event.inputs.deployment != "site" && github.event.inputs.deployment != "modmail-bot"
        run: |
          echo Invalid deployment specified.
          exit 1
          
  start_notification:
    name: "Deployment start notification"
    runs-on: ubuntu-latest
    
    steps:
      - name: Deployment start notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: "@${{ github.event.sender.login }} has requested a redeployment of `${{ github.event.inputs.deployment }}`."
          
  redeploy_service:
    name: "Deploy service"
    runs-on: ubuntu-latest
    needs: [validate_job, start_notification]
    
    steps:
      - name: Authenticate with Kubernetes
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
          
      - name: Redeploy service
        run: kubectl rollout restart deployment ${{ github.event.inputs.deployment }}
          
  end_notification:
    name: "Deployment finish notification"
    runs-on: ubuntu-latest
    
    steps:
      - name: Deployment finish notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: "@${{ github.event.sender.login }} has finished a redeployment of `${{ github.event.inputs.deployment }}`."
